[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.unsplash.com; img-src 'self' data: *.unsplash.com; style-src 'self' 'unsafe-inline';"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.generateArticle]
  schedule = "0 */12 * * *"

[context.production.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"